CREATE TABLE `student` (
	`studentId`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`studentFirstName`	TEXT NOT NULL,
	`studentMiddleName`	TEXT,
	`studentLastName`	TEXT NOT NULL,
	`genderId`	INTEGER NOT NULL,
	`studentDateBirth`	TEXT NOT NULL,
	`raceId`	INTEGER NOT NULL,
	`studentBirthPlaceLocalityCountryId`	INTEGER NOT NULL DEFAULT 1,
	`studentBirthPlaceLocalityStateId`	INTEGER NOT NULL,
	`studentBirthPlaceLocalityCityId`	INTEGER NOT NULL,
	`studentBirthCertificateId`	TEXT NOT NULL,
	`studentAddressZipCode`	INTEGER NOT NULL,
	`studentAddressStreet`	TEXT NOT NULL,
	`studentAddressSubDivision`	TEXT NOT NULL,
	`studentAddressCompletement`	TEXT NOT NULL DEFAULT 'N/A',
	`studentAddressLocalityCountryId`	INTEGER NOT NULL DEFAULT 1,
	`studentAddressLocalityStateId`	INTEGER NOT NULL,
	`studentAddressLocalityCityId`	INTEGER NOT NULL,
	`studentMotherName`	TEXT NOT NULL,
	`studentMotherGovernmentId`	TEXT NOT NULL,
	`studentMotherSchoolingId`	INTEGER NOT NULL,
	`studentMotherDateBirth`	TEXT NOT NULL,
	`studentMotherProfession`	TEXT NOT NULL,
	`studentMotherPhoneNum`	TEXT NOT NULL,
	`studentFatherName`	TEXT,
	`studentFatherGovernmentId`	TEXT,
	`studentFatherSchoolingId`	INTEGER,
	`studentFatherDateBirth`	TEXT,
	`studentFatherProfession`	TEXT,
	`studentFatherPhoneNum`	TEXT,
	`studentEmergencyPhoneNum01`	TEXT NOT NULL,
	`studentEmergencyContactName01`	TEXT NOT NULL,
	`studentEmergencyPhoneNum02`	TEXT,
	`studentEmergencyContactName02`	TEXT,
	`studentObservations`	TEXT,
	`studentPhotoFileName`	TEXT,
	`studentHadChickenpox`	INTEGER NOT NULL DEFAULT 0,
	`studentHadRubella`	INTEGER NOT NULL DEFAULT 0,
	`studentHadDehydration`	INTEGER NOT NULL DEFAULT 0,
	`studentHadMumps`	INTEGER NOT NULL DEFAULT 0,
	`studentHadOtherContagiousDiseaseDesc`	TEXT NOT NULL DEFAULT 'N/A',
	`studentHasAlergies`	TEXT NOT NULL DEFAULT 'N/A',
	`studentHasCardiacDiseases`	TEXT NOT NULL DEFAULT 'N/A',
	`studentHasNeurologicalDiseases`	TEXT NOT NULL DEFAULT 'N/A',
	`studentHasAuditiveDeficency`	INTEGER NOT NULL DEFAULT 0,
	`studentHasVisualDeficency`	INTEGER NOT NULL DEFAULT 0,
	`studentHasMentalDeficency`	INTEGER NOT NULL DEFAULT 0,
	`studentHasMotorDeficency`	INTEGER NOT NULL DEFAULT 0,
	`studentHasBrochitisOrAsthma`	INTEGER NOT NULL DEFAULT 0,
	`studentHasRecurringDiarrhea`	INTEGER NOT NULL DEFAULT 0,
	`studentHasConvulsions`	INTEGER NOT NULL DEFAULT 0,
	`studentNeedConstantMedicalSupervision`	TEXT NOT NULL DEFAULT 'N/A',
	`educationCenterId01`	INTEGER,
	`groupId01`	INTEGER,
	`studentEnrollmentDate01`	TEXT,
	`studentEnrollmentGuardianName01`	TEXT,
	`studentEnrollmentSchoolCoordinatorName01`	TEXT,
	`enrollmentStatusId01`	INTEGER,
	`educationCenterId02`	INTEGER,
	`groupId02`	INTEGER,
	`studentEnrollmentDate02`	TEXT,
	`studentEnrollmentGuardianName02`	TEXT,
	`studentEnrollmentSchoolCoordinatorName02`	TEXT,
	`enrollmentStatusId02`	INTEGER,
	`educationCenterId03`	INTEGER,
	`groupId03`	INTEGER,
	`studentEnrollmentDate03`	TEXT,
	`studentEnrollmentGuardianName03`	TEXT,
	`studentEnrollmentSchoolCoordinatorName03`	TEXT,
	`enrollmentStatusId03`	INTEGER,
	`educationCenterId04`	INTEGER,
	`groupId04`	INTEGER,
	`studentEnrollmentDate04`	TEXT,
	`studentEnrollmentGuardianName04`	TEXT,
	`studentEnrollmentSchoolCoordinatorName04`	TEXT,
	`enrollmentStatusId04`	INTEGER,
	`educationCenterId05`	INTEGER,
	`groupId05`	INTEGER,
	`studentEnrollmentDate05`	TEXT,
	`studentEnrollmentGuardianName05`	TEXT,
	`studentEnrollmentSchoolCoordinatorName05`	TEXT,
	`enrollmentStatusId05`	INTEGER,
	`educationCenterId06`	INTEGER,
	`groupId06`	INTEGER,
	`studentEnrollmentDate06`	TEXT,
	`studentEnrollmentGuardianName06`	TEXT,
	`studentEnrollmentSchoolCoordinatorName06`	TEXT,
	`enrollmentStatusId06`	INTEGER,
	FOREIGN KEY(`genderId`) REFERENCES `gender`(`genderId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`raceId`) REFERENCES `race`(`raceId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`studentBirthPlaceLocalityCountryId`) REFERENCES `LocalityCountry`(`LocalityCountryId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`studentBirthPlaceLocalityStateId`) REFERENCES `LocalityState`(`LocalityStateId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`studentBirthPlaceLocalityCityId`) REFERENCES `LocalityCity`(`LocalityCityId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`studentAddressLocalityCountryId`) REFERENCES `LocalityCountry`(`LocalityCountryId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`studentAddressLocalityStateId`) REFERENCES `LocalityState`(`LocalityStateId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`studentAddressLocalityCityId`) REFERENCES `LocalityCity`(`LocalityCityId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`studentMotherSchoolingId`) REFERENCES `Schooling`(`SchoolingId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`studentFatherSchoolingId`) REFERENCES `Schooling`(`SchoolingId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`educationCenterId01`) REFERENCES `educationCenter`(`educationCenterId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`groupId01`) REFERENCES `group`(`groupId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`enrollmentStatusId01`) REFERENCES `enrollmentStatus`(`enrollmentStatusId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`educationCenterId02`) REFERENCES `educationCenter`(`educationCenterId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`groupId02`) REFERENCES `group`(`groupId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`enrollmentStatusId02`) REFERENCES `enrollmentStatus`(`enrollmentStatusId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`educationCenterId03`) REFERENCES `educationCenter`(`educationCenterId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`groupId03`) REFERENCES `group`(`groupId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`enrollmentStatusId03`) REFERENCES `enrollmentStatus`(`enrollmentStatusId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`educationCenterId04`) REFERENCES `educationCenter`(`educationCenterId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`groupId04`) REFERENCES `group`(`groupId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`enrollmentStatusId04`) REFERENCES `enrollmentStatus`(`enrollmentStatusId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`educationCenterId05`) REFERENCES `educationCenter`(`educationCenterId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`groupId05`) REFERENCES `group`(`groupId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`enrollmentStatusId05`) REFERENCES `enrollmentStatus`(`enrollmentStatusId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`educationCenterId06`) REFERENCES `educationCenter`(`educationCenterId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`groupId06`) REFERENCES `group`(`groupId`) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY(`enrollmentStatusId06`) REFERENCES `enrollmentStatus`(`enrollmentStatusId`) ON DELETE RESTRICT ON UPDATE RESTRICT
);

INSERT INTO `student`
(
	`studentId`,
	`studentFirstName`,
	`studentMiddleName`,
	`studentLastName`,
	`genderId`,
	`studentDateBirth`,
	`raceId`,
	`studentBirthPlaceLocalityCountryId`,
	`studentBirthPlaceLocalityStateId`,
	`studentBirthPlaceLocalityCityId`,
	`studentBirthCertificateId`,
	`studentAddressZipCode`,
	`studentAddressStreet`,
	`studentAddressSubDivision`,
	`studentAddressCompletement`,
	`studentAddressLocalityCountryId`,
	`studentAddressLocalityStateId`,
	`studentAddressLocalityCityId`,
	`studentMotherName`,
	`studentMotherGovernmentId`,
	`studentMotherSchoolingId`,
	`studentMotherDateBirth`,
	`studentMotherProfession`,
	`studentMotherPhoneNum`,
	`studentFatherName`,
	`studentFatherGovernmentId`,
	`studentFatherSchoolingId`,
	`studentFatherDateBirth`,
	`studentFatherProfession`,
	`studentFatherPhoneNum`,
	`studentEmergencyPhoneNum01`,
	`studentEmergencyContactName01`,
	`studentEmergencyPhoneNum02`,
	`studentEmergencyContactName02`,
	`studentObservations`,
	`studentPhotoFileName`,
	`studentHadChickenpox`,
	`studentHadRubella`,
	`studentHadDehydration`,
	`studentHadMumps`,
	`studentHadOtherContagiousDiseaseDesc`,
	`studentHasAlergies`,
	`studentHasCardiacDiseases`,
	`studentHasNeurologicalDiseases`,
	`studentHasAuditiveDeficency`,
	`studentHasVisualDeficency`,
	`studentHasMentalDeficency`,
	`studentHasMotorDeficency`,
	`studentHasBrochitisOrAsthma`,
	`studentHasRecurringDiarrhea`,
	`studentHasConvulsions`,
	`studentNeedConstantMedicalSupervision`,
	--
	`educationCenterId01`,
	`groupId01`,
	`studentEnrollmentDate01`,
	`studentEnrollmentGuardianName01`,
	`studentEnrollmentSchoolCoordinatorName01`,
	`enrollmentStatusId01`,
	--
	`educationCenterId02`,
	`groupId02`,
	`studentEnrollmentDate02`,
	`studentEnrollmentGuardianName02`,
	`studentEnrollmentSchoolCoordinatorName02`,
	`enrollmentStatusId02`,
	--
	`educationCenterId03`,
	`groupId03`,
	`studentEnrollmentDate03`,
	`studentEnrollmentGuardianName03`,
	`studentEnrollmentSchoolCoordinatorName03`,
	`enrollmentStatusId03`,
	--
	`educationCenterId04`,
	`groupId04`,
	`studentEnrollmentDate04`,
	`studentEnrollmentGuardianName04`,
	`studentEnrollmentSchoolCoordinatorName04`,
	`enrollmentStatusId01`,
	--
	`educationCenterId05`,
	`groupId05`,
	`studentEnrollmentDate05`,
	`studentEnrollmentGuardianName05`,
	`studentEnrollmentSchoolCoordinatorName05`,
	`enrollmentStatusId05`,
	--
	`educationCenterId06`,
	`groupId06`,
	`studentEnrollmentDate06`,
	`studentEnrollmentGuardianName06`,
	`studentEnrollmentSchoolCoordinatorName06`,
	`enrollmentStatusId06`
) VALUES
(
1, -- 	`studentId`,
'Gabriel', -- 	`studentFirstName`,
'Santana de Castro', -- 	`studentMiddleName`,
'Jardim', -- 	`studentLastName`,
2, -- 	`genderId`,
'1993-09-11', -- 	`studentDateBirth`,
5, -- 	`raceId`,
1, -- 	`studentBirthPlaceLocalityCountryId`,
9, -- 	`studentBirthPlaceLocalityStateId`,
977, -- 	`studentBirthPlaceLocalityCityId`,
'1993-09-11', -- 	`studentBirthCertificateId`,
74230030, -- 	`studentAddressZipCode`,
'Avenida T 4', -- 	`studentAddressStreet`,
'Setor Bueno', -- 	`studentAddressSubDivision`,
'Goiânia', -- 	`studentAddressCompletement`,
1, -- 	`studentAddressLocalityCountryId`,
9, -- 	`studentAddressLocalityStateId`,
977, -- 	`studentAddressLocalityCityId`,
'Viviane Santana Silva Jardim', -- 	`studentMotherName`,
'222', -- 	`studentMotherGovernmentId`,
4, -- 	`studentMotherSchoolingId`,
'1972-06-02', -- 	`studentMotherDateBirth`,
'Trainer', -- 	`studentMotherProfession`,
'(563)288-0223', -- 	`studentMotherPhoneNum`,
'Luciano de Castro Jardim', -- 	`studentFatherName`,
'333', -- 	`studentFatherGovernmentId`,
4, -- 	`studentFatherSchoolingId`,
'1967-11-26', -- 	`studentFatherDateBirth`,
'Programmer', -- 	`studentFatherProfession`,
'(563)288-0223', -- 	`studentFatherPhoneNum`,
'62-3281-5148', -- 	`studentEmergencyPhoneNum01`,
'Maristela de Castro Jardim', -- 	`studentEmergencyContactName01`,
NULL, -- 	`studentEmergencyPhoneNum02`,
NULL, -- 	`studentEmergencyContactName02`,
NULL, -- 	`studentObservations`,
NULL, -- 	`studentPhotoFileName`,
1, -- 	`studentHadChickenpox`,
0, -- 	`studentHadRubella`,
0, -- 	`studentHadDehydration`,
0, -- 	`studentHadMumps`,
'N/A', -- 	`studentHadOtherContagiousDiseaseDesc`,
'N/A', -- 	`studentHasAlergies`,
'N/A', -- 	`studentHasCardiacDiseases`,
'N/A', -- 	`studentHasNeurologicalDiseases`,
0, -- 	`studentHasAuditiveDeficency`,
0, -- 	`studentHasVisualDeficency`,
0, -- 	`studentHasMentalDeficency`,
0, -- 	`studentHasMotorDeficency`,
0, -- 	`studentHasBrochitisOrAsthma`,
0, -- 	`studentHasRecurringDiarrhea`,
0, -- 	`studentHasConvulsions`,
'N/A', -- 	`studentNeedConstantMedicalSupervision`,
-- 	--
1, -- 	`educationCenterId01`,
1, -- 	`groupId01`,
'2017-07-01', -- 	`studentEnrollmentDate01`,
'Neide de Santana', -- 	`studentEnrollmentGuardianName01`,
'Kezia', -- 	`studentEnrollmentSchoolCoordinatorName01`,
1, -- 	`enrollmentStatusId01`,
-- 	--
NULL, -- 	`educationCenterId02`,
NULL, -- 	`groupId02`,
NULL, -- 	`studentEnrollmentDate02`,
NULL, -- 	`studentEnrollmentGuardianName02`,
NULL, -- 	`studentEnrollmentSchoolCoordinatorName02`,
NULL, -- 	`enrollmentStatusId02`,
-- 	--
NULL, -- 	`educationCenterId03`,
NULL, -- 	`groupId03`,
NULL, -- 	`studentEnrollmentDate03`,
NULL, -- 	`studentEnrollmentGuardianName03`,
NULL, -- 	`studentEnrollmentSchoolCoordinatorName03`,
NULL, -- 	`enrollmentStatusId03`,
-- 	--
NULL, -- 	`educationCenterId04`,
NULL, -- 	`groupId04`,
NULL, -- 	`studentEnrollmentDate04`,
NULL, -- 	`studentEnrollmentGuardianName04`,
NULL, -- 	`studentEnrollmentSchoolCoordinatorName04`,
NULL, -- 	`enrollmentStatusId01`,
-- 	--
NULL, -- 	`educationCenterId05`,
NULL, -- 	`groupId05`,
NULL, -- 	`studentEnrollmentDate05`,
NULL, -- 	`studentEnrollmentGuardianName05`,
NULL, -- 	`studentEnrollmentSchoolCoordinatorName05`,
NULL, -- 	`enrollmentStatusId05`,
-- 	--
NULL, -- 	`educationCenterId06`,
NULL, -- 	`groupId06`,
NULL, -- 	`studentEnrollmentDate06`,
NULL, -- 	`studentEnrollmentGuardianName06`,
NULL, -- 	`studentEnrollmentSchoolCoordinatorName06`,
NULL -- 	`enrollmentStatusId06`
)
;
